version: '3.7'

services:
  coding_excercise:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - /home/node/app/node_modules
    container_name: coding_excercise
    expose:
      - '3009'
    ports:
      - '3009:3009'
    command: npm run dev